window.cards = {
"whiteCards": [
"Coat hanger abortions.",
"Man meat.",
"Autocannibalism.",
"Vigorous jazz hands.",
"Flightless birds.",
"Pictures of boobs.",
"Doing the right thing.",
"The violation of our most basic human rights.",
"Viagra&reg;.",
"Self-loathing.",
"Spectacular abs.",
"A balanced breakfast.",
"Roofies.",
"Concealing a boner.",
"Amputees.",
"The Big Bang.",
"Former President George W. Bush.",
"The Rev. Dr. Martin Luther King, Jr.",
"Smegma.",
"Being marginalized.",
"Cuddling.",
"Laying an egg.",
"The Pope.",
"Aaron Burr.",
"Genital piercings.",
"Fingering.",
"A bleached asshole.",
"Horse meat.",
"Fear itself.",
"Science.",
"Elderly Japanese men.",
"Stranger danger.",
"The terrorists.",
"Praying the gay away.",
"Same-sex ice dancing.",
"Ethnic cleansing.",
"Cheating in the Special Olympics.",
"German dungeon porn.",
"Bingeing and purging.",
"Making a pouty face.",
"William Shatner.",
"Heteronormativity.",
"Nickelback.",
"Tom Cruise.",
"The profoundly handicapped.",
"The placenta.",
"Chainsaws for hands.",
"Arnold Schwarzenegger.",
"An icepick lobotomy.",
"Goblins.",
"Object permanence.",
"Dying.",
"Foreskin.",
"A falcon with a cap on its head.",
"Hormone injections.",
"Dying of dysentery.",
"Sexy pillow fights.",
"The invisible hand.",
"A really cool hat.",
"Sean Penn.",
"Heartwarming orphans.",
"The clitoris.",
"The Three-Fifths compromise.",
"A sad handjob.",
"Men.",
"Historically black colleges.",
"A micropenis.",
"Raptor attacks.",
"Agriculture.",
"Vikings.",
"Pretending to care.",
"The Underground Railroad.",
"My humps.",
"Being a dick to children.",
"Geese.",
"Bling.",
"Sniffing glue.",
"The South.",
"An Oedipus complex.",
"Eating all of the cookies before the AIDS bake-sale.",
"Sexting.",
"YOU MUST CONSTRUCT ADDITIONAL PYLONS.",
"Mutually-assured destruction.",
"Sunshine and rainbows.",
"Count Chocula.",
"Sharing needles.",
"Being rich.",
"Skeletor.",
"A sausage festival.",
"Michael Jackson.",
"Emotions.",
"Farting and walking away.",
"The Chinese gymnastics team.",
"Necrophilia.",
"Spontaneous human combustion.",
"Yeast.",
"Leaving an awkward voicemail.",
"Dick Cheney.",
"White people.",
"Penis envy.",
"Teaching a robot to love.",
"Sperm whales.",
"Scrubbing under the folds.",
"Panda sex.",
"Whipping it out.",
"Catapults.",
"Masturbation.",
"Natural selection.",
"Opposable thumbs.",
"A sassy black woman.",
"AIDS.",
"The KKK.",
"Figgy pudding.",
"Seppuku.",
"Gandhi.",
"Preteens.",
"Toni Morrison's vagina.",
"Five-Dollar Footlongs&trade;.",
"Land mines.",
"A sea of troubles.",
"A zesty breakfast burrito.",
"Christopher Walken.",
"Friction.",
"Balls.",
"Dental dams.",
"A can of whoop-ass.",
"A tiny horse.",
"Waiting 'til marriage.",
"Authentic Mexican cuisine.",
"Genghis Khan.",
"Old-people smell.",
"Feeding Rosie O'Donnell.",
"Pixelated bukkake.",
"Friends with benefits.",
"The token minority.",
"The Tempur-Pedic&reg; Swedish Sleep System&trade;.",
"A thermonuclear detonation.",
"Take-backsies.",
"The Rapture.",
"A cooler full of organs.",
"Sweet, sweet vengeance.",
"RoboCop.",
"Keanu Reeves.",
"Drinking alone.",
"Giving 110%.",
"Flesh-eating bacteria.",
"The American Dream.",
"Taking off your shirt.",
"Me time.",
"A murder most foul.",
"The inevitable heat death of the universe.",
"The folly of man.",
"That thing that electrocutes your abs.",
"Cards Against Humanity.",
"Fiery poops.",
"Poor people.",
"Edible underpants.",
"Britney Spears at 55.",
"All-you-can-eat shrimp for $4.99.",
"Pooping back and forth. Forever.",
"Fancy Feast&reg;.",
"Jewish fraternities.",
"Being a motherfucking sorcerer.",
"Pulling out.",
"Picking up girls at the abortion clinic.",
"The homosexual agenda.",
"The Holy Bible.",
"Passive-agression.",
"Ronald Reagan.",
"Vehicular manslaughter.",
"Nipple blades.",
"Assless chaps.",
"Full frontal nudity.",
"Hulk Hogan.",
"Daddy issues.",
"The hardworking Mexican.",
"Natalie Portman.",
"Waking up half-naked in a Denny's parking lot.",
"God.",
"Sean Connery.",
"Saxophone solos.",
"Gloryholes.",
"The World of Warcraft.",
"Homeless people.",
"Scalping.",
"Darth Vader.",
"Eating the last known bison.",
"Guys who don't call.",
"Hot Pockets&reg;.",
"A time travel paradox.",
"The milk man.",
"Testicular torsion.",
"Dropping a chandelier on your enemies and riding the rope up.",
"World peace.",
"A salty surprise.",
"Poorly-timed Holocaust jokes.",
"Smallpox blankets.",
"Licking things to claim them as your own.",
"The heart of a child.",
"Robert Downey, Jr.",
"Lockjaw.",
"Eugenics.",
"A good sniff.",
"Friendly fire.",
"The taint; the grundle; the fleshy fun-bridge.",
"Wearing underwear inside-out to avoid doing laundry.",
"Hurricane Katrina.",
"Free samples.",
"Jerking off into a pool of children's tears.",
"A foul mouth.",
"The glass ceiling.",
"Republicans.",
"Explosions.",
"Michelle Obama's arms.",
"Getting really high.",
"Attitude.",
"Sarah Palin.",
"The &Uuml;bermensch.",
"Altar boys.",
"My soul.",
"My sex life.",
"Pedophiles.",
"72 virgins.",
"Pabst Blue Ribbon.",
"Domino's&trade; Oreo&trade; Dessert Pizza.",
"A snapping turtle biting the tip of your penis.",
"The Blood of Christ.",
"Half-assed foreplay.",
"My collection of high-tech sex toys.",
"A middle-aged man on roller skates.",
"Bitches.",
"Bill Nye the Science Guy.",
"Italians.",
"A windmill full of corpses.",
"Adderall&trade;.",
"Crippling debt.",
"A stray pube.",
"Prancing.",
"Passing a kidney stone.",
"A brain tumor.",
"Leprosy.",
"Puppies!",
"Bees?",
"Frolicking.",
"Repression.",
"Road head.",
"A bag of magic beans.",
"An asymmetric boob job.",
"Dead parents.",
"Public ridicule.",
"A mating display.",
"A mime having a stroke.",
"Stephen Hawking talking dirty.",
"African children.",
"Mouth herpes.",
"Overcompensation.",
"Riding off into the sunset.",
"Being on fire.",
"Tangled Slinkys.",
"Civilian casualties.",
"Auschwitz.",
"My genitals.",
"Not reciprocating oral sex.",
"Lactation.",
"Being fabulous.",
"Shaquille O'Neal's acting career.",
"My relationship status.",
"Asians who aren't good at math.",
"Alcoholism.",
"Incest.",
"Grave robbing.",
"Hope.",
"8 oz. of sweet Mexican black-tar heroin.",
"Kids with ass cancer.",
"Winking at old people.",
"The Jews.",
"Justin Bieber.",
"Doin' it in the butt.",
"A lifetime of sadness.",
"The Hamburglar.",
"Swooping.",
"Classist undertones.",
"New Age music.",
"Not giving a shit about the Third World.",
"The Kool-Aid Man.",
"A hot mess.",
"Tentacle porn.",
"Lumberjack fantasies.",
"The gays.",
"Scientology.",
"Estrogen.",
"GoGurt&reg;.",
"Judge Judy.",
"Dick fingers.",
"Racism.",
"Surprise sex!",
"Police brutality.",
"Passable transvestites.",
"The Virginia Tech Massacre.",
"When you fart and a little bit comes out.",
"Oompa-Loompas.",
"A fetus.",
"Obesity.",
"Tasteful sideboob.",
"Hot people.",
"BATMAN!!!",
"Black people.",
"A gassy antelope.",
"Sexual tension.",
"Third base.",
"Racially-biased SAT questions.",
"Porn stars.",
"A Super Soaker&trade; full of cat pee.",
"Muhammed (Praise Be Unto Him).",
"Puberty.",
"A disappointing birthday party.",
"An erection that lasts longer than four hours.",
"White privilege.",
"Getting so angry that you pop a boner.",
"Wifely duties.",
"Two midgets shitting into a bucket.",
"Queefing.",
"Wiping her butt.",
"Golden showers.",
"Barack Obama.",
"Nazis.",
"A robust mongoloid.",
"An M. Night Shyamalan plot twist.",
"Getting drunk on mouthwash.",
"Lunchables&trade;.",
"Women in yogurt commercials.",
"John Wilkes Booth.",
"Powerful thighs.",
"Mr. Clean, right behind you.",
"Multiple stab wounds.",
"Cybernetic enhancements.",
"Serfdom.",
"Kanye West.",
"Women's suffrage.",
"Children on leashes.",
"Harry Potter erotica.",
"The Dance of the Sugar Plum Fairy.",
"Lance Armstrong's missing testicle.",
"Parting the Red Sea.",
"The Amish.",
"Dead babies.",
"Child beauty pageants.",
"AXE Body Spray.",
"Centaurs.",
"Copping a feel.",
"Grandma.",
"Famine.",
"The Trail of Tears.",
"The miracle of childbirth.",
"Finger painting.",
"A monkey smoking a cigar.",
"The Make-A-Wish&reg; Foundation.",
"Anal beads.",
"The Force.",
"Kamikaze pilots.",
"Dry heaving.",
"Active listening.",
"Ghosts.",
"The Hustle.",
"Peeing a little bit.",
"Another goddamn vampire movie.",
"Shapeshifters.",
"The Care Bear Stare.",
"Hot cheese.",
"A mopey zoo lion.",
"A defective condom.",
"Teenage pregnancy.",
"A Bop It&trade;.",
"Expecting a burp and vomiting on the floor.",
"Horrifying laser hair removal accidents.",
"Boogers.",
"Unfathomable stupidity.",
"Breaking out into song and dance.",
"Soup that is too hot.",
"Morgan Freeman's voice.",
"Getting naked and watching Nickelodeon.",
"MechaHitler.",
"Flying sex snakes.",
"The true meaning of Christmas.",
"My inner demons.",
"Pac-Man uncontrollably guzzling cum.",
"My vagina.",
"A homoerotic volleyball montage.",
"Actually taking candy from a baby.",
"Crystal meth.",
"Exactly what you'd expect.",
"Natural male enhancement.",
"Passive-aggressive Post-it notes.",
"Inappropriate yodeling.",
"Lady Gaga.",
"The Little Engine That Could.",
"Vigilante justice.",
"A death ray.",
"Poor life choices.",
"A gentle caress of the inner thigh.",
"Embryonic stem cells.",
"Nicolas Cage.",
"Firing a rifle into the air while balls deep in a squealing hog.",
"Switching to Geico&reg;.",
"The chronic.",
"Erectile dysfunction.",
"Home video of Oprah sobbing into a Lean Cuisine&reg;.",
"A bucket of fish heads.",
"50,000 volts straight to the nipples.",
"Being fat and stupid.",
"Hospice care.",
"A pyramid of severed heads.",
"Getting married, having a few kids, buying some stuff, retiring to Florida, and dying.",
"A subscription to Men's Fitness.",
"Crucifixion.",
"A micropig wearing a tiny raincoat and booties.",
"Some god-damn peace and quiet.",
"Used panties.",
"A tribe of warrior women.",
"The penny whistle solo from \"My Heart Will Go On.\"",
"An oversized lollipop.",
"Helplessly giggling at the mention of Hutus and Tutsis.",
"Not wearing pants.",
"Consensual sex.",
"Her Majesty, Queen Elizabeth II.",
"Funky fresh rhymes.",
"The art of seduction.",
"The Devil himself.",
"Advice from a wise, old black man.",
"Destroying the evidence.",
"The light of a billion suns.",
"Wet dreams.",
"Synergistic management solutions.",
"Growing a pair.",
"Silence.",
"An M16 assault rifle.",
"Poopy diapers.",
"A live studio audience.",
"The Great Depression.",
"A spastic nerd.",
"Rush Limbaugh's soft, shitty body.",
"Tickling Sean Hannity, even after he tells you to stop.",
"Stalin.",
"Brown people.",
"Rehab.",
"Capturing Newt Gingrich and forcing him to dance in a monkey suit.",
"Battlefield amputations.",
"An uppercut.",
"Shiny objects.",
"An ugly face.",
"Menstrual rage.",
"A bitch slap.",
"One trillion dollars.",
"Chunks of dead prostitute.",
"The entire Mormon Tabernacle Choir.",
"The female orgasm.",
"Extremely tight pants.",
"The Boy Scouts of America.",
"Stormtroopers.",
"Throwing a virgin into a volcano.",
"Getting in her pants, politely.",
"Gladiatorial combat.",
"Good grammar.",
"Hipsters.",
"Gandalf.",
"Genetically engineered super-soldiers.",
"George Clooney's musk.",
"Getting abducted by Peter Pan.",
"Eating an albino.",
"Enormous Scandinavian women.",
"Fabricating statistics.",
"Finding a skeleton.",
"Suicidal thoughts.",
"Dancing with a broom.",
"Deflowering the princess.",
"Dorito breath.",
"One thousand Slim Jims.",
"My machete.",
"Overpowering your father.",
"Ominous background music.",
"Media coverage.",
"Making the penises kiss.",
"Moral ambiguity.",
"Medieval Times&reg; Dinner &amp; Tournament.",
"Mad hacky-sack skills.",
"Just the tip.",
"Literally eating shit.",
"Leveling up.",
"Insatiable bloodlust.",
"Historical revisionism.",
"Jean-Claude Van Damme.",
"Jafar.",
"The boners of the elderly.",
"The economy.",
"Statistically validated stereotypes.",
"Sudden Poop Explosion Disease.",
"Slow motion.",
"Space muffins.",
"Sexual humiliation.",
"Sexy Siamese twins.",
"Santa Claus.",
"Scrotum tickling.",
"Ripping into a man's chest and pulling out his still-beating heart.",
"Ryan Gosling riding in on a white horse.",
"Quivering jowls.",
"Revenge fucking.",
"Pistol-whipping a hostage.",
"Quiche.",
"Zeus's sexual appetites.",
"Words, words, words.",
"Tripping balls.",
"Being a busy adult with many important things to do.",
"The four arms of Vishnu.",
"The shambling corpse of Larry King.",
"The hiccups.",
"The harsh light of day.",
"The Gulags.",
"The Fanta&reg; girls.",
"A big black dick.",
"A beached whale.",
"A low standard of living.",
"A nuanced critique.",
"A bloody pacifier.",
"A crappy little hand.",
"Shaft.",
"Being a dinosaur.",
"Beating your wives.",
"Neil Patrick Harris.",
"Coughing into a vagina.",
"Carnies.",
"Nubile slave boys.",
"Bosnian chicken farmers.",
"A web of lies.",
"A rival dojo.",
"A passionate Latino lover.",
"Panty raids.",
"Appreciative snapping.",
"Apologizing.",
"Clams.",
"A woman scorned.",
"Being awesome at sex.",
"Spring break!",
"Another shot of morphine.",
"Dining with cardboard cutouts of the cast of \"Friends.\"",
"A soulful rendition of \"Ol' Man River.\"",
"Making a friend.",
"A sweaty, panting leather daddy.",
"Intimacy problems.",
"The new Radiohead album.",
"Pretty Pretty Princess Dress-Up Board Game&reg;.",
"A man in yoga pants with a ponytail and feather earrings.",
"An army of skeletons.",
"A squadron of moles wearing aviator goggles.",
"Beefin' over turf.",
"The Google.",
"Bullshit.",
"A sweet spaceship.",
"A 55-gallon drum of lube.",
"Special musical guest, Cher.",
"The human body.",
"Mild autism.",
"Nunchuck moves.",
"Whipping a disobedient slave.",
"An ether-soaked rag.",
"Oncoming traffic.",
"A dollop of sour cream.",
"A slightly shittier parallel universe.",
"My first kill.",
"Boris the Soviet Love Hammer.",
"The grey nutrient broth that sustains Mitt Romney.",
"Tiny nipples.",
"Power.",
"Death by Steven Seagal.",
"A Burmese tiger pit.",
"Basic human decency.",
"Grandpa's ashes.",
"One Ring to rule them all.",
"The day the birds attacked.",
"Fetal alcohol syndrome.",
"Graphic violence, adult language, and some sexual content.",
"A bigger, blacker dick.",
"The mere concept of Applebee's&reg;.",
"A sad fat dragon with no friends.",
"A pi&ntilde;ata full of scorpions.",
"Existing.",
"Hillary Clinton's death stare.",
"Catastrophic urethral trauma.",
"Double penetration.",
"Daddy's belt.",
"Swiftly achieving orgasm.",
"Mooing.",
"Rising from the grave.",
"Subduing a grizzly bear and making her your wife.",
"Some really fucked-up shit.",
"Weapons-grade plutonium.",
"All of this blood.",
"Scrotal frostbite.",
"Taking a man's eyes and balls out and putting his eyes where his balls go and then his balls in the eye holes.",
"The mixing of the races.",
"Pumping out a baby every nine months.",
"Tongue.",
"Loki, the trickster god.",
"Whining like a little bitch.",
"Wearing an octopus for a hat.",
"An unhinged ferris wheel rolling toward the sea.",
"Finding Waldo.",
"Upgrading homeless people to mobile hotspots.",
"A magic hippie love cloud.",
"Fuck Mountain.",
"Living in a trashcan.",
"The corporations.",
"Getting hilariously gang-banged by the Blue Man Group.",
"Jeff Goldblum.",
"Survivor's guilt.",
"Me.",
"All my friends dying.",
"Shutting the fuck up.",
"An ass disaster.",
"Some kind of bird-man.",
"The entire Internet.",
"Going around punching people.",
"A boo-boo.",
"Indescribable loneliness.",
"Having sex on top of a pizza.",
"Chugging a lava lamp.",
"Warm, velvety muppet sex.",
"Running naked through a mall, pissing and shitting everywhere.",
"Nothing.",
"Samuel L. Jackson.",
"Self-flagellation.",
"The systematic destruction of an entire people and their way of life.",
"The Quesadilla Explosion Salad&trade; from Chili's&reg;.",
"Reverse cowgirl.",
"Vietnam flashbacks.",
"Actually getting shot, for real.",
"Not having sex.",
"Cock.",
"Dying alone and in pain.",
"A cop who is also a dog.",
"The way white people is.",
"Gay aliens.",
"The primal, ball-slapping sex your parents are having right now.",
"A cat video so cute that your eyes roll back and your spine slides out of your anus.",
"A lamprey swimming up the toilet and latching onto your taint.",
"Slapping a racist old lady.",
"A black male in his early 20s, last seen wearing a hoodie.",
"Jumping out at people.",
"Three months in the hole.",
"Blood farts.",
"The Land of Chocolate.",
"A botched circumcision.",
"My manservant, Claude.",
"Vomiting mid-blowjob.",
"Letting everyone down.",
"Having shotguns for legs.",
"Bill Clinton, naked on a bearskin rug with a saxophone.",
"Mufasa's death scene.",
"The Harlem Globetrotters.",
"Demonic possession.",
"Fisting.",
"The thin veneer of situational causality that underlies porn.",
"Girls that always be textin'.",
"Blowing some dudes in an alley.",
"A spontaneous conga line.",
"A vagina that leads to another dimension.",
"Disco fever.",
"Getting your dick stuck in a Chinese finger trap with another dick.",
"Drinking ten 5-hour ENERGYs&reg; to get fifty continuous hours of energy.",
"Sneezing, farting, and coming at the same time.",
"Some douche with an acoustic guitar.",
"Spending lots of money.",
"Putting an entire peanut butter and jelly sandwich into the VCR.",
"An unstoppable wave of fire ants.",
"A greased-up Matthew McConaughey.",
"Flying robots that kill people.",
"Unlimited soup, salad, and breadsticks.",
"Crying into the pages of Sylvia Plath.",
"The moist, demanding chasm of his mouth.",
"Filling every orifice with butterscotch pudding.",
"An all-midget production of Shakespeare's <i>Richard III</i>.",
"Screaming like a maniac.",
"Not contributing to society in any meaningful way.",
"A pile of squirming bodies.",
"Buying the right pants to be cool.",
"Roland the Farter, flatulist to the king.",
"That ass.",
"A surprising amount of hair.",
"Eating Tom Selleck's mustache to gain his powers.",
"Velcro&trade;.",
"A PowerPoint presentation.",
"Crazy opium eyes.",
"10 Incredible Facts About the Anus.",
"An interracial handshake.",
"Moderate-to-severe joint pain.",
"Finally finishing off the Indians.",
"Sugar madness.",
"Actual mutants with medical conditions and no superpowers.",
"The secret formula for ultimate female satisfaction.",
"The complex geopolitical quagmire that is the Middle East.",
"Fucking a corpse back to life.",
"Neil Diamond's Greatest Hits.",
"Calculating every mannerism so as not to suggest homosexuality.",
"Whatever a McRib&reg; is made of.",
"No clothes on, penis in vagina.",
"All the single ladies.",
"Whispering all sexy.",
"How awesome I am.",
"Ass to mouth.",
"Smoking crack, for instance.",
"Falling into the toilet.",
"A dance move that's just sex.",
"The size of my penis.",
"Some sort of Asian.",
"A hopeless amount of spiders.",
"Party Mexicans.",
"Drinking responsibly.",
"The safe word.",
"Angelheaded hipsters burning for the ancient heavenly connection to the starry dynamo in the machinery of night.",
"Bouncing up and down.",
"Jizz.",
"Ambiguous sarcasm.",
"A shiny rock that proves I love you.",
"Dem titties.",
"My worthless son.",
"Exploding pigeons.",
"A Ugandan warlord.",
"My sex dungeon.",
"A kiss on the lips.",
"Child Protective Services.",
"A Native American who solves crimes by going into the spirit world.",
"Doo-doo.",
"The peaceful and nonthreatening rise of China.",
"Sports.",
"A fart.",
"Unquestioning obedience.",
"Three consecutive seconds of happiness.",
"Grammar nazis who are also regular Nazis.",
"Snorting coke off a clown's boner.",
"Africa.",
"Depression.",
"A horse with no legs.",
"The euphoric rush of strangling a drifter.",
"Khakis.",
"Interspecies marriage.",
"A gender identity that can only be conveyed through slam poetry.",
"Almost giving money to a homeless person.",
"Stuff a child's face with Fun Dip&reg; until he starts having fun.",
"What Jesus would do.",
"A for-real lizard that spits blood from its eyes.",
"Blackula.",
"The tiniest shred of evidence that God is real.",
"My dad's dumb fucking face.",
"Prince Ali,<br>fabulous he,<br>Ali Ababwa.",
"A manhole.",
"A sex goblin with a carnival penis.",
"A bunch of idiots playing a card game instead of interacting like normal humans.",
"A sex comet from Neptune that plunges the Earth into eternal sexiness.",
"Sharks with legs.",
"Injecting speed into one arm and horse tranquilizer into the other.",
"Lots and lots of abortions.",
"Seeing things from Hitler's perspective",
"Too much cocaine.",
"Doing the right stuff to her nipples.",
"Giant sperm from outer space.",
"Oil!",
"Ennui.",
"A powered exoskeleton.",
"A disappointing salad.",
"Mom's new boyfriend.",
"Unrelenting genital punishment.",
"Denzel.",
"The swim team, all at once.",
"The eight gay warlocks who dictate the rules of fashion.",
"Being nine years old.",
"The unbelievable world of mushrooms.",
"The Abercrombie &amp; Fitch lifestyle.",
"Vegetarian options.",
"My first period.",
"Having been dead for a while.",
"Backwards knees.",
"Being paralyzed from the neck down.",
"Seeing my village burned and my family slaughtered before my eyes.",
"A zero-risk way to make $2,000 from home.",
"A crazy little thing called love.",
"Ancient Athenian boy-fucking",
"Out-of-this-world bazongas.",
"The ghost of Marlon Brando.",
"The basic suffering that pervades all of existence.",
"Being worshipped as the one true God.",
"Figuring out how to have sex with a dolphin.",
"All these decorative pillows.",
"A mouthful of potato salad.",
"Russian super-tuberculosis.",
"A reason not to commit suicide.",
"Going to a high school reunion on ketamine.",
"The passage of time.",
"Child support payments.",
"Changing a person's mind with logic and facts.",
"My boyfriend's stupid penis.",
"The tiger that killed my father.",
"Genghis Khan's DNA.",
"Boring vaginal sex.",
"40 acres and a mule.",
"A whole new kind of porn.",
"Slowly easing down onto a cucumber.",
"Wearing glasses and sounding smart.",
"AIDS monkeys.",
"A team of lawyers.",
"Getting drive-by shot.",
"Not believing in giraffes.",
"Anal fissures like you wouldn't believe.",
"A giant powdery manbaby.",
"Cutting off a flamingo's legs with garden shears.",
"P.F. Chang himself.",
"An uninterrupted history of imperialism and exploitation.",
"A one-way ticket to Gary, Indiana.",
"Daddy's credit card.",
"September 11th, 2001.",
"An unforgettable quincea&ntilde;era.",
"Deez nuts.",
"Social justice warriors with flamethrowers of compassion.",
"Some shit-hot guitar licks.",
"Butt stuff.",
"Blackface.",
"Blowjobs for everyone.",
"Getting eaten alive by Guy Fieri.",
"Western standards of beauty.",
"Ejaculating live bees and the bees are angry.",
"My dead son's baseball glove.",
"Getting caught by the police and going to jail.",
"A face full of horse cum.",
"Free ice cream, yo.",
"The white half of Barack Obama.",
"The black half of Barack Obama.",
"An inability to form meaningful relationships.",
"A bass drop so huge it tears the starry vault asunder to reveal the face of God.",
"Growing up chained to a radiator in perpetual darkness.",
"Shitting all over the floor like a bad, bad girl.",
"A buttload of candy.",
"Sucking all the milk out of a yak.",
"Bullets.",
"A man who is so cool that he rides on a motorcycle.",
"Sudden penis loss.",
"Getting all offended.",
"Crying and shitting and eating spaghetti.",
"One unforgettable night of passion.",
"Being popular and good at sports.",
"Filling a man's anus with concrete.",
"Two whales fucking the shit out of eachother.",
"Cool, relateable cancer teens.",
"The amount of gay I am.",
"A possible Muslim.",
"Unsheathing my massive horse cock.",
"A bowl of gourds.",
"The male gaze.",
"The power of the Dark Side.",
"Ripping a dog in half.",
"A constant need for validation.",
"Meaningless sex.",
"Such a big boy.",
"Throwing stones at a man until he dies.",
"Cancer.",
"Like a million alligators.",
"Eating together like a god damn family for once.",
"Cute boys.",
"Pussy.",
"Being a terrible mother.",
"Never having sex again.",
"A pizza guy who fucked up.",
"A whole lotta woman.",
"The all-new Nissan Pathfinder with 0.9% APR financing!",
"A peyote-fueled vision quest.",
"Kale.",
"Breastfeeding a ten year old.",
"Crippling social anxiety.",
"Immortality cream.",
"Texas.",
"Teaching a girl how to handjob the penis.",
"A turd.",
"Shapes and colors.",
"Whatever you wish, mother.",
"The haunting stare of an Iraqi child.",
"Robots who just want to party.",
"A self-microwaving burrito.",
"Forgetting grandma's first name.",
"Our new Buffalo Chicken Dippers&reg;!",
"Treasures beyond your wildest dreams.",
"Getting shot out of a cannon.",
"The sweet song of sword against and the braying of mighty war beasts.",
"Walking into a glass door.",
"The color \"puce\".",
"Every ounce of charisma left in Mick Jagger's tired body.",
"The eighth graders.",
"Setting my balls on fire and cartwheeling to Ohio.",
"The dentist.",
"Gwyneth Paltrow's opinions.",
"Turning the rivers red with the blood of infidels.",
"Rabies.",
"Important news about Taylor Swift.",
"Ejaculating inside another man's wife.",
"Owls, the perfect predator.",
"Being John Malkovich.",
"Bathing in moonsblood and dancing around the ancient oak.",
"An oppressed people with a vibrant culture.",
"An overwhelming variety of cheeses.",
"Reading the entire End-User License Agreement.",
"Morpheus.",
"Peeing into a girl's butt to make a baby.",
"Generally having no idea of what's going on.",
"No longer finding any Cards Against Humanity card funny.",
"10 football players with erections barreling towards you at full speed.",
"10,000 shrieking teenage girls.",
"A big ol' plate of fettuccine alfredo.",
"A big, beautiful mouth packed to the brim with sparkling teeth.",
"A black friend.",
"A burrito that's just sour cream.",
"A cheerfulness that belies a deep-seated self-loathing.",
"A cold and indifferent universe.",
"A creature made of penises that must constantly arouse itself to survive.",
"A creepy child singing a nursery rhyme.",
"A dolphin that learns to talk and becomes the Dead of Harvard Law School.",
"A duffel bag full of lizards.",
"A finger up the butt.",
"A genetic predisposition for alcoholism.",
"A gun that shoots cobras.",
"A hug.",
"A long business meeting with no obvious purpose.",
"A man in a suit with perfect hair who tells you beautiful lies.",
"A man with the head of a goat and the body of a goat.",
"A massive collection of child pornography.",
"A medium horchata.",
"A negative body image that is totally justified.",
"A slowly encroaching circle of wolves.",
"A strong horse and enough rations for thirty days.",
"A terrified fat child who won't come out of the bushes.",
"A tiny fireman who puts out tiny fires.",
"A weird guy who says weird stuff and weirds me out.",
"A woman's right to choose.",
"A woman's perspective.",
"Aborting the shit out of a fetus.",
"Albert Einstein but if he had a huge muscles and a rhinoceros cock.",
"All these people I've killed.",
"An arrangement wherein I give a person money they have sex with me.",
"An empowered woman.",
"An incurable homosexual.",
"An old dog full of tumors.",
"An older man.",
"An X-Man whose power is that he has sex with dogs and children.",
"Anal.",
"Antidepressants.",
"Art.",
"Assassinating the president.",
"Awesome pictures of planets and stuff.",
"Bad emotions I don't want.",
"Becoming the President of the United States.",
"Being sexually attracted to children.",
"Being turned into sausages.",
"Beyonc&eacute;.",
"Big, smart money boys tap-tapping on their keyboards.",
"Blossoming into a beautiful young woman.",
"Breastfeeding in public like a radiant earth goddess.",
"Brunch.",
"Catching a live salmon in your mouth.",
"Child labor.",
"China.",
"Chipotle.",
"Chris Hemsworth.",
"Comprehensive immigration reform.",
"Condoleezza Rice.",
"Consensual, nonreproductive incest.",
"Content.",
"Crazy anal orgasms.",
"Creamy slices of real, California avocado.",
"Critical thinking.",
"Crushing the patriarchy.",
"Daddy going away forever.",
"Defeating a gorilla in single combat.",
"Denying the Holocaust.",
"Dis bitch.",
"Discovering that what I really want in life is to kill people and have sex with their corpses.",
"Doing a somersault and barfing.",
"Dominating a man by peeing on his eldest son.",
"Doritos and a Fruit Roll-Up.",
"Dropping dead in a Sbarro's bathroom and not being found for 72 hours.",
"Dumpster juice.",
"Eating ass.",
"Eating people.",
"Eating too many Cinnabons and then vomiting and then eating the vomit.",
"Ejaculating at the apex of a cartwheel.",
"Esmeralda, my most beautiful daughter.",
"Eternal screaming madness.",
"Every man's ultimate fantasy: a perfectly cylindrical vagina.",
"Everything.",
"Exploring each other's buttholes.",
"Facilitating dialogue and deconstructing binaries.",
"Falling into a pit of waffles.",
"Farting a huge shit out of my pussy.",
"Farting all over my face with your tight little asshole.",
"Feeling the emotion of anger.",
"Feminism.",
"Film roles for actresses over 40.",
"Finding a nice elevator to poop in.",
"Forty-five minutes of finger blasting.",
"Founding a major world religion.",
"Fucking me good and taking me to Red Lobster&reg;.",
"Fucking my therapist.",
"Gary.",
"Gay thoughts.",
"Gayle from HR.",
"Gazpacho.",
"Getting aborted.",
"Getting blasted in the face by a t-shirt cannon.",
"Getting eaten out by a dog.",
"Getting high with mom.",
"Getting killed and dragged up a tree by a leopard.",
"Getting laid like all the time.",
"Getting naked too soon.",
"Getting pegged.",
"Getting the Dorito crumbs out of my purse.",
"Getting this party started!",
"Getting trapped in a conversation about Ayn Rand.",
"Going around pulling people's tampons out.",
"Going to bed at a reasonable hour.",
"Gregor, my largest son.",
"Grunting for ten minutes and then peeing sand.",
"Guns.",
"Happy daddies with happy sandals.",
"Hating Jews.",
"Having a vagina.",
"Having an awesome time drinking and driving.",
"Having sex with a beautiful person.",
"Having sex with a man and then eating his head.",
"Having sex with your mom.",
"Holding the proper political beliefs of my time to attract a mate.",
"Homework.",
"Hot lettuce.",
"How good lead paint taste.",
"How great my ass looks in these jeans.",
"How sad it will be when Morgan Freeman dies.",
"How strange it is to be anything at all.",
"Huge big balls full of jizz.",
"Informing you that I am a registered sex offender.",
"ISIS.",
"It being too late to stop having sex with a horse.",
"Jason, the teen mayor.",
"Jazz.",
"Just now finding out about the Armenian Genocide.",
"Late-stage dementia.",
"Libertarians.",
"Loud, scary thunder.",
"Making out and stuff.",
"Math.",
"Meatloaf, the food.",
"Meatloaf, the man.",
"Menopause.",
"Mental illness.",
"Microaggressions.",
"Misogyny.",
"Mixing M&Ms and Skittles like some kind of psychopath.",
"Mommy and daddy fighting all the time.",
"Moon people.",
"Muchin' puss.",
"My brother's hot friends.",
"My dog dying.",
"My huge penis and substantial fortune.",
"Objectifying women.",
"One of them big-city Jew lawyers.",
"One of those \"blow jobs\" I've been hearing so much about.",
"Onions.",
"Opening your mouth to talk and a big penis fops out.",
"Our baby.",
"Out-of-control teenage blowjob parties.",
"Overthrowing the democratically-elected government of Chile.",
"Participating.",
"Period poops.",
"Picking up a glass of water and taking a sip and being the president.",
"Playing my asshole like a trumpet.",
"Plowing that ass like a New England corn farmer.",
"Political correctness.",
"Pooping in a leotard and hoping no one notices.",
"Pooping in the potty.",
"Prematurely ejaculating like a total loser.",
"Pretending to be one of the guys but actually being the spider god.",
"Putting more black people in jail.",
"Quacking like a duck in lieu of a cogent argument.",
"Quinoa.",
"Raising three kids on minimum wage.",
"Reaching an age where barbecue chips are better than sex.",
"Regurgitating a half-digested sparrow.",
"Restoring Germany to its former glory.",
"Rock-hard tits and a huge vagina.",
"Rolling so hard.",
"Rubbing my bush all over your bald head.",
"Salsa Night at Dave's Cantina.",
"Scissoring, if that's a thing.",
"Seizing control of the means of production.",
"Self-identifying as a DJ.",
"Showing all the boys my pussy.",
"Slamming a dunk.",
"Smashing my balls at the moment of climax.",
"Some of that good dick.",
"Some real spicy shrimps.",
"Starting a shitty podcast.",
"Straight blazin' 24/7.",
"Sucking each other's penises for hours on end.",
"Sudden and unwanted slam poetry.",
"Swearing praise upon the Sultan's hideous daughters.",
"Systems and policies designed to preserve centuries-old power structures.",
"Tables.",
"Taking the form of a falcon.",
"Tender chunks of all-white-meat chicken.",
"That bitch, Stacy.",
"The amount of baby carrots I can fit up my ass.",
"The best, deepest quotes from The Dark Knight.",
"The body of a 46-year-old man.",
"The bond between a woman and her horse.",
"The chicken from Popeyes&reg;.",
"The clown that followed me home from the grocery store.",
"The fear and hatred in men's hearts.",
"The feeling of going to McDonald's as a 6-year-old.",
"The flaming wreckage of the International Space Station.",
"The full blown marginalization of ugly people.",
"The full force of the American military.",
"The government.",
"The graceful path of an autumn leaf as it falls to its earthen cradle.",
"The hottest MILF in Dallas.",
"The LGBT community.",
"The lived experience of African Americans.",
"The mysterious fog rolling into town.",
"The ol' penis-in-the-popcorn surprise.",
"The Rwandan Genocide.",
"The secret to truly resilient hair.",
"The sweet, forbidden meat of the monkey.",
"The wind.",
"Thinking about what eating even is.",
"Three hours of nonstop penetration.",
"Tiny, rancid girl farts.",
"Trees.",
"Trevor, the world's greatest boyfriend.",
"Turning 32.",
"Twenty bucks.",
"Twenty cheerleaders laughing at your tiny penis.",
"Twisting my cock and balls into a balloon poodle.",
"Two beautiful pig sisters.",
"Two shitty kids and a garbage husband.",
"Waking up inside of a tornado.",
"Watching a hot person eat.",
"Watching you die.",
"Water.",
"When the big truck goes \"Toot! Toot!\"",
"Who really did 9/11.",
"Whomsoever let the dogs out.",
"Whooping your ass at Mario Kart.",
"Working so hard to have muscles and then having them.",
"You.",
"Several Michael Keatons.",
"A bus that will explode if it goes under 50 miles per hour.",
"Sucking the President's dick.",
"Sunny D! Alright!",
"A mulatto, an albino, a mosquito, and my libido.",
"Log&trade;.",
"Jerking off to a 10-second RealMedia clip.",
"The Y2K bug.",
"Deregulating the mortgage market.",
"Stabbing the shit out of a Capri Sun.",
"Wearing Nicolas Cage's face.",
"Freeing Willy.",
"Kurt Cobain's death.",
"The Great Cornholio.",
"Liking big butts and not being able to lie about it.",
"Yelling \"girl power!\" and doing a high kick.",
"Pure Moods, Vol. 1.",
"Pizza in the morning, pizza in the evening, pizza at supper time.",
"Pamela Anderson's boobs running in slow motion.",
"Getting caught up in the CROSSFIRE&trade;.",
"Angels interfering in an otherwise fair baseball game.",
"Cool 90s up-in-the-front hair.",
"Patti Mayonnaise.",
"The biggest, blackest dick.",
"A box within a box.",
"A boxing match with a giant box.",
"A box.",
"Pandora's vagina.",
"Former President George W. Box.",
"Being a motherfucking box.",
"A falcon with a box on its head.",
"Two midgets shitting into a box.",
"A box without hinges, key, or lid, yet golden treasure inside is hid.",
"The J15 Patriot Assault Box.",
"An alternate universe in which boxes store things inside of people.",
"A box that is conscious and wishes it weren't a box.",
"Something that looks like a box but turns out to be a crate.",
"A man-shaped box.",
"A box-shaped man.",
"Boxing up my feelings.",
"A world without boxes.",
"The Boxcar Children.",
"An outbreak of smallbox.",
"A box of biscuits, a box of mixed biscuits, and a biscuit mixer.",
"A CGI dragon.",
"A dwarf who won't leave you alone until you compare penis sizes.",
"A gay sorcerer who turns everyone gay.",
"A ghoul.",
"A Hitachi Magic Wand.",
"A magical kingdom with dragons and elves and no black people.",
"A mysterious, floating orb.",
"A weed elemental who gets everyone high.",
"Accidentally conjuring a legless horse that can't stop ejaculating.",
"Bathng naked in a moonlit grove.",
"Dinosaurs who wear armor and you ride them and they kick ass.",
"Eternal darkness.",
"Freaky, pan-dimensional sex with a demigod.",
"Gender equality.",
"Going on an epic adventure and learning a valuable lesson about friendship.",
"Handcuffing a wizard to a radiator and dousing him with kerosene.",
"Hodor.",
"How hot Orlando Bloom was in <i>Lord of the Rings</i>.",
"Kneeing a wizard in the balls.",
"Make-believe stories for autistic white men,",
"Reading The Hobbit under the covers while mom and dad scream at each other downstairs.",
"Shitting in a wizard's spell book and jizzing in his hat.",
"Shooting a wizard with a gun.",
"The all-seeing Eye of Sauron.",
"The card game Neil Gaiman wrote: \"Three elves at a time.\"",
"True love's kiss.",
"A sobering quantity of chili cheese fries.",
"Going vegetarian and feeling so great all the time.",
"Kale farts.",
"Licking the cake batter off of grandma's fingers.",
"Real cheese flavor.",
"Swishing the wine around and sniffing it like a big fancy man.",
"The Dial-A-Slice Apple Divider from Williams-Sonoma.",
"What to do with all of this chocolate on my penis.",
"A belly full of hard-boiled eggs.",
"A joyless vegan patty.",
"A table for one at The Cheesecake Factory.",
"Being emotionally and physically dominated by Gordon Ramsay.",
"Kevin Bacon Bits.",
"Not knowing what to believe anymore about butter.",
"Soup that's better than pussy.",
"Sucking down thousands of pounds of krill every day.",
"A Mexican child trapped inside of a burrito.",
"Clamping down on a gazelle's jugular and tasting its warm life waters.",
"Committing suicide at the Old Country Buffet.",
"Father's forbidden chocolates.",
"Jizz Twinkies.",
"The Hellman's Mayonnaise Corporation.",
"The hot dog I put in my vagina ten days ago.",
"The inaudible screams of carrots.",
"A supermassive black hole.",
"Reconciling quantum theory with general relativity.",
"Electroejaculating a capuchin monkey.",
"Insufficient serotonin.",
"Evolving a labyrinthine vagina.",
"Getting really worried about global warming for a few seconds.",
"Infinity.",
"Oxytocin release via manual stimulation of the nipples.",
"Uranus.",
"Being knowledgeable in a narrow domain that nobody understands or cares about.",
"Achieving reproductive success.",
"Slowly evaporating.",
"The quiet majesty of the sea turtle.",
"A 0.7 waist-to-hip ratio.",
"Fun and interesting facts about rocks.",
"Photosynthesis.",
"Developing secondary sex characteristics.",
"Failing the Turing test.",
"Explosive decompression.",
"Driving into a tornado to learn about tornadoes.",
"David Attenborough watching us mate.",
"3.7 billion years of evolution.",
"The Sun engulfing the Earth.",
"A complete inability to understand anyone else's perspective.",
"A fun, sexy time at the nude beach.",
"A man from Craigslist.",
"A night of Taco Bell and anal sex.",
"A respectful discussion of race and gender on the Internet.",
"Cat massage.",
"Destroying Dick Cheney's last horcrux.",
"<i>Game of Thrones</i> spoilers.",
"Getting teabagged by a fifth grader in Call of Duty.",
"Goats screaming like people.",
"Googling.",
"Internet porn analysis paralysis.",
"Matching with Mom on Tinder.",
"My browser history.",
"My privileged white penis.",
"Pretending to be black.",
"Smash Mouth.",
"Taking a shit while running at full speed.",
"That thing on the Internet everyone's talking about.",
"Three years of semen in a shoebox.",
"YouTube comments.",
"The Bernie Sanders revolution.",
"Letting Bernie Sanders rest his world-weary head on your lap.",
"A beautiful, ever-expanding circle of inclusivity that will never include Republicans.",
"Black lives mattering.",
"Donald Trump holding his nose while he eats pussy.",
"The fact that Hillary Clinton is a woman.",
"Kicking the middle class in the balls with a regressive tax code.",
"Keeping the government out of my vagina.",
"The systematic disenfranchisement of black voters.",
"Increasing economic and political polarization",
"Eating the president's pussy.",
"Actually voting for Donald Trump to be President of the actual United States.",
"A liberal bias.",
"Hating Hillary Clinton.",
"Growing up and becoming a Republican.",
"Courageously going ahead with that racist comment.",
"Dispelling this fiction that Barack Obama doesn't know what he's doing.",
"Jeb!",
"The good, hardworking people of Dubuque, Iowa.",
"Conservative talking points.",
"Shouting the loudest",
"Sound of fiscal policy.",
"Full-on socialism.",
"A legitimate reason to commit suicide.",
"A back-alley abortion from a Mexican cyborg doctor.",
"Whipping lower-class white men into a xenophobic frenzy.",
"Rage.",
"Trying to remember what music was.",
"Roaming through a wasteland of windblown trash and deserted highways.",
"Bringing millions of dangerous low-paying manufacturing jobs back to America.",
"A gnawing sense of dread.",
"Drinking urine to survive.",
"Nuclear winter.",
"President Donald Trump.",
"Casual dismissiveness.",
"Extra rations for my little girl.",
"World Wars 3 through 5.",
"Finding out that democracy might not be such a great idea.",
"Mild amusement.",
"Burying my only son.",
"The purging of the disloyal.",
"Trying to wake up from this nightmare.",
"A father and son fighting each other over the last scrap of bread.",
"Making Islam illegal.",
"Desperately hurling insults at Donald Trump as he absorbs them into his rapidly expanding body.",
"Forcing a handjob on a dying man. ",
"A homoerotic subplot.",
"An origami swan that's some kind of symbol?",
"25 shitty jokes about House of Cards.",
"My constituents.",
"Punching a congressman in the face.",
"Strangling a dog to make a point to the audience.",
"A childless marriage.",
"A much younger woman.",
"Getting eaten out while on the phone with Dad.",
"Making it look like a suicide.",
"Carbon monoxide poisoning. ",
"Discharging a firearm in a residential area.",
"Ribs so good they transcend race and class.",
"The sensitive European photographer who's fucking my wife.",
"Blaring Gangnam Style on repeat.",
"Low sperm motility.",
"A drunk relative muttering racial slurs.",
"The sudden need to conceal a massive boner.",
"A long, awkward pause before she says \"I do.\"",
"A see-through wedding gown.",
"A pair of rusty handcuffs and a bottle of lube.",
"That bridesmaid that won't stop crying.",
"A good old-fashioned case of whiskey dick.",
"Undying love and eternal affection.",
"Herpes.",
"Your father-in-law's erectile dysfunction pills.",
"Holding hands when you get old.",
"Swinging.",
"Cat-like night vision.",
"Not knowing what a rusty trombone is.",
"Finding out you're actually cousins.",
"Saving yourself for marriage.",
"Over 5,000 flavored condoms.",
"Unplanned pregnancy!",
"Getting high and making out.",
"Married sex.",
"Vaginal juices.",
"A tasteful spray tan.",
"A gag ball and a riding crop.",
"Way too much sensual massage oil.",
"Premature ejaculation.",
"One too many blow job shots.",
"Skinny dipping in a vat of bubble solution.",
"Your creepy uncle with the wandering hands.",
"That time the bride thought she was a lesbian.",
"Life in a nudist vegan hippie commune.",
"Deep existential loneliness.",
"Post-coital bliss.",
"Too damn many kids.",
"A \"business trip.\"",
"A little too much glitter.",
"Testosterone-induced rage.",
"A drunk karaoke version of \"Take My Breath Away\".",
"A groomsman in a kilt ...and nothing else.",
"A half-finished Brazilian wax job.",
"Being kind of hormonal.",
"Running out of things to talk about.",
"Paralyzing, all-consuming fear of commitment.",
"Leaving little love notes around the house.",
"Unicorns and lollipops.",
"Sleeping with your therapist.",
"The Chicken Dance.",
"A hickey from a stripper.",
"Drinking your troubles away nightly.",
"High-fiving after sex.",
"Nipple clamps on the gift registry.",
"Refusing to shave.",
"Sleeping on the couch.",
"Falling a little more in love every day forever.",
"Faking a pregnancy.",
"Making out in public.",
"A mustache ride.",
"Long walks at sunset ON DRUGS.",
"Far too many dildos.",
"A penis that's almost too big.",
"Fighting over whether or not you're fighting.",
"Multiple orgasms.",
"Doing what Jesus would do.",
"Storm trooper centerpieces.",
"Marrying an axe murderer.",
"Hogging the bathroom.",
"Some innocent wife-swapping among friends.",
"Weekly date nights at the local BDSM dungeon.",
"Falling asleep during oral sex.",
"Not remembering your wedding night.",
"A little same-sex experimentation.",
"A three-way in Vegas.",
"Talking dirty in a Spanish accent.",
"A raging libido.",
"Going black, and never going back.",
"The best man dressed in drag.",
"A heart-shaped Jacuzzi filled with champagne and Viagra&trade;.",
"Secretly drunk-dialing exes.",
"Sexercise.",
"Changing both your last names to \"Danger.\"",
"Forgetting the safe word.",
"Praying and reading the Torah.",
"Bad dragon erotica.",
"An elaborate alien abduction fantasy.",
"A godless harlot.",
"Praying and reading the Bible.",
"Martha Stewart.",
"That dirty weekend in Cabo.",
"Unconditional love.",
"The challenge of balancing career and family.",
"Don Draper.",
"A pound of weed and a Mexican stripper.",
"Sex on the kitchen table.",
"Unleashing the vixen within.",
"Delirious, infectious happiness.",
"Fighting over the remote control.",
"Getting kicked out of your own wedding reception.",
"A lifetime of judgmental glances from your in-laws.",
"A colorful assortment of butt plugs.",
"Being too hung-over for a hand job.",
"Getting a dog.",
"A thousand shitty wedding-planning websites.",
"The best man's dark sexual past.",
"Forgetting your birth control pills.",
"Decorating the house with vagina-inspired artwork.",
"A hot neighbor with no conscience and nothing to lose.",
"A severed finger in the wedding cake.",
"A solid five-year plan.",
"Breaking the hymen.",
"A penis with a smiley face.",
"A misunderstanding involving a strap-on.",
"Someone getting arrested.",
"A happy ending.",
"Getting tired of being on top.",
"A forged prescription for STD meds.",
"Sharing a bank account.",
"Wondering if you made the right decision.",
"Gratuitous PDA on Facebook.",
"Getting a pube stuck in your teeth.",
"Rephrasing it as an \"I feel\" statement.",
"Pooping with the door open.",
"A hasty vasectomy.",
"A botched genital piercing.",
"An unacceptable volume of body hair.",
"A DJ with a Wham! obsession.",
"A mysterious stain on his tuxedo.",
"PMS-ing at the altar.",
"A timeless reading from Fifty Shades of Grey.",
"Walking down the aisle to \"Baby Got Back.\"",
"Your unborn children.",
"Someone using the word \"Bridezilla\" one more goddamn time.",
"A lifetime subscription to Big Black Butts magazine.",
"The secret handshake.",
"Mowing the fucking lawn.",
"Blaming it on the dog.",
"A nervous breakdown at IKEA&trade;.",
"A healthy work-life balance.",
"Several decades of festering resentment.",
"Really letting yourself go.",
"Wondering who's gonna die first.",
"The wedding-industrial complex.",
"Hiding the M&M's&reg;.",
"\"Intimacy issues.\"",
"Just giving up.",
"A 50% divorce rate.",
"Keeping tabs. Always keeping tabs.",
"Making a big fat deal out of nothing.",
"A butthole full of mustard.",
"Unwavering support for your career.",
"A small price to pay for half off the catering.",
"People constantly telling you that marriage is a lot of work.",
"Faking it until making it.",
"Wedding crashers passing out Ecstasy to your elderly relatives.",
"A maid of honor with no shame. No. Shame.",
"Winking at waitresses.",
"A diamond the size of Uranus.",
"Forgetting your anniversary, year after year.",
"Wishing this moment could last forever.",
"Hyperventilating at the gynecologist's office.",
"Cashing in the kids' college fund to pay off your substantial gambling debts.",
"A secret second family in Canada.",
"Sharing all your most embarrassing secrets. Except one.",
"A groomsman confessing he always secretly loved you.",
"Your dad showing up drunk. Like always.",
"His prostate.",
"Realizing the Kama Sutra is actually really lame.",
"Knowing way too much about each other's bathroom habits.",
"Things you can never unsee.",
"Wishing you were half as happy as your social media posts make you seem.",
"Texting instead of talking.",
"Grocery shopping in a bathrobe.",
"The happiest man on Earth.",
"Meaning something completely different by the word \"facial.\"",
"Staying up all night talking.",
"Wondering where that rash came from.",
"Pretending you were just kidding.",
"Seven tubs of ass wax.",
"All the sacrifices that come with it.",
"Low self-esteem.",
"Each other.",
"Blood on the sheets.",
"Saying \"Me so horny!\" in a Yoda voice.",
"Open, honest communication.",
"Gay marriage.",
"Tickle-fight-induced vomiting.",
"Passive-aggressive notes on the fridge.",
"Homoerotic undertones.",
"Getting caught masturbating to hentai porn.",
"Ranch dressing.",
"A quivering pile of love jelly.",
"Putting the cats in the pre-nup.",
"Taking things too literally.",
"Daily reminders about who actually pays the mortgage.",
"Meeting the weekly cunnilingus quota.",
"A demonstration of who really wears the pants in this family.",
"A daily, futile power struggle.",
"A bizarre love octagon.",
"A digital chastity belt.",
"Too little, too late.",
"A lifetime of crippling regret.",
"Make-up sex.",
"Whisper-fighting in the kitchen.",
"A pale slurry of tears, icing, and denial.",
"The ceremonial spanking of the bride.",
"Mormons.",
"A veil made out of duct tape.",
"Hearing the same jokes over and over again for all eternity.",
"Finding your soul mate.",
"A reluctant, eye-rolling apology.",
"A disturbingly life-like blow-up doll.",
"Adultery.",
"Coveting your neighbor's polyamorous lifestyle.",
"A mediocre dominatrix.",
"Wearing a t-shirt that says \"I TOLD YOU SO.\"",
"Lower expectations.",
"CheapRussianBrides.com.",
"Naked aggression.",
"A shrieking biological alarm clock.",
"Fairy-themed cosplay.",
"A waterproof, vibrating attachment.",
"A heart made of sentient nanobots.",
"Foreplay.",
"Neanderthal mating habits.",
"Admitting defeat.",
"Feelings of inadequacy.",
"A top-shelf prostitute.",
"Matching  denim outfits.",
"Motherfucking cupcakes.",
"Ring finger tattoos.",
"Fish fingering your custard.",
"The hideousness that is Raxacoricofallapatorious.",
"An Ood getting a starring role in a hentai.",
"Christopher Eccleston.",
"Matt Smith.",
"A kid in a gas mask asking if you are his mummy.",
"Siltheen farts.",
"The big banana in your pocket.",
"Taking a Doctor Poo.",
"David Tennant.",
"Opening the door of the TARDIS and leaving a deuce in the time-space continuum.",
"Low-budget special effects.",
"River Song.",
"Dalek porn.",
"Eggs.",
"Finding Autons oddly attractive.",
"THE END OF TIME ITSELF!",
"Glenn Beck convulsively puking as a brood of Daleks swarm in on him.",
"The fuck machine dungeon of the Cybermen.",
"Fifty years of fanfic.",
"Just now realizing Torchwood is an anagram of Doctor Who",
"The Doctor going back in time to solve a REAL problem: Twilight.",
"Wanting to punch that teeny-bopper Whovian that's butthurt the new Doctor isn't in his twenties.",
"The Silence",
"A Doctor Who body pillow.",
"A Rusty Cyberman",
"Drunkenly drawing tally marks on your face.",
"The Doctor having a chance encounter with a couple of 80s metalheads.",
"A shitty Doctor Who knock-knock joke.",
"The Master, baiting the Doctor into a trap",
"Davros getting up on the wrong side of the bed.",
"Wishing you could regenerate.",
"A Vashta Nerada that just wants a hug.",
"The poor costume decisions that were the 1970s.",
"Kidnapping a barely-legal woman to time travel with.",
"Tom Baker, in nothing but a scarf",
"Walking in on Jack Harkness doing your mom. And your dad.",
"The buzzing noise the Sonic Screwdriver makes",
"Sharing a public restroom with a Weeping Angel",
"A bigger, bluer TARDIS.",
"K-9 humping your leg.",
"The Master singing Bad Case of Loving You.",
"Rose Tyler's teeth.",
"A GUITARDIS",
"A fez caked with semen.",
"Robot Anne Robinson.",
"Steven Moffatt taking a big old dump in your Cheerios.",
"Fapping to Billie Piper portraying a callgirl.",
"Your dyslexic friend that wants you to come watch a marathon of Doctor How.",
"Captain Jack Harkness.",
"The Celestial Toymaker's plaything.",
"A global simulcast that forces Whovians to see the sunlight for the first time in ages.",
"A Costco-sized bag of Jelly Babies.",
"Being used as a plot device by Steven Moffat.",
"A furry writing BAD WOLF everywhere.",
"Quitting this panel after one round because you are afraid of getting typecast.",
"The Mary Jane Adventures.",
"Sixteen feet of scarf bondage.",
"Getting so much plastic surgery you have to be framed and moisturized.",
"Smoking 1,000 cigarettes, just so you can sound like a Dalek when you talk.",
"Slipping her the ol' plastic Mickey.",
"Fondling a Dalek's slippery bits.",
"Air from my lungs.",
"A Sonic Screwdriver stuck on the vibrate setting.",
"Pouting in a rain storm and having to take a wicked piss.",
"Companion Porn.",
"An acid rain shower on Skaro.",
"Plot holes so wide you could drive a truck through them.",
"A blinged out TARDIS blasting dubstep when it is traveling.",
"The poor decision that is having a staring contest with a weeping angel.",
"Sorry, this answer is only available in the fanfic version of Cards against Con.",
"Jaime Lannister, 'The Kingslayer'.",
"Cersei Lannister, the Queen.",
"Joffrey Baratheon, the Prince.",
"Tyrion Lannister, 'The Imp'.",
"Ned Stark, Lord of Winterfell, Warden of the North.",
"Robb Stark, heir apparent of Winterfell.",
"Jon Snow, the bastard.",
"Catelyn Stark, Lady of Winterfell.",
"Sansa Stark, betrothed to Prince Joffrey.",
"Arya Stark.",
"Bran Stark.",
"The Wall.",
"The Night's Watch.",
"Danerys Targaryen, Khaleesi of the Dothraki.",
"Theon Greyjoy, Ned Stark's youthful ward.",
"Peter 'Littlefinger' Baelish.",
"Lord Varys, the Spider.",
"King Robert Baratheon, First of His Name, King of the Andals and the First Men, Lord Protector of the Realm.",
"Khal Drogo, Dothraki horse lord.",
"The Iron Throne.",
"HODOR!!",
"Ros, the red-headed whore.",
"Winterfell.",
"Kings's Landing.",
"The North.",
"Beyond the Wall.",
"Westeros.",
"The Seven Kingdoms.",
"Direwolves.",
"White Walkers.",
"Dragons.",
"'Winter is Coming'.",
"The old gods and the new.",
"Incest, hot twin on twin action.",
"House Stark.",
"House Lannister.",
"House Targaryen.",
"George R. R. Martin.",
"Gratuitous nudity, the way only HBO&reg; can provide.",
"Throwing a boy out of a window to cover up incest.",
"Joining the Night's Watch.",
"Selling your sister to Dothraki nomads.",
"Making your husband love you through cunning use of reverse cowgirl.",
"Running a whorehouse, which is better than owning ships.",
"Conquering the continent with dragons.",
"Being forced to marry an abusive king.",
"Beheading a man for having no honor.",
"Explaining complicated plot with lots of naked women around.",
"Trusting Littlefinger.",
"Learning the prince is a bastard and the product of incest.",
"Slapping Joffrey. Repeatedly.",
"Cutting off your enemies' heads and mounting them on spikes.",
"Raising your husband's bastard son as your own.",
"Asking a teenage girl if she's 'bled yet'.",
"Making millions of fans cry by killing off beloved characters.",
"Hodoring.",
"Riding off to join your best friend's rebellion.",
"Breastfeeding your creepy son until he's 9 years old.",
"Having a giant wolf for a pet.",
"Beheaded on the steps of the Sept of Baelor.",
"Killed by a member of the Kingsguard.",
"Seized the Iron Throne by any means necessary.",
"Built a 700 foot high wall to keep out bad things.",
"Born a bastard.",
"Butchered by White Walkers and arranged in an artful pattern.",
"Appointed as Hand of the King.",
"Found enough wolf cubs for all the children.",
"Fondled by your brother on your wedding day.",
"Climbed the wrong wall at the wrong time.",
"Started a pointless vendetta with another House.",
"Increased ratings with the use of gratuitous nudity.",
"Carried by Hodor.",
"Pissed off of the Wall just because.",
"Swore an oath to the old gods and the new.",
"Brought home a new baby bastard for your wife to hate.",
"Negotiated a wedding no one will like.",
"Rode a dragon, like a boss.",
"Changed things from the book, infuriating fans.",
"Spent an entire reign chasing boars and fucking whores.",
"Zero F**K's Given!",
"Windows update",
"Wilfrord Brimley's Mustache",
"Wikileaks",
"Why not Zoidberg?!",
"White Shirt",
"Warp core breach",
"W.O.P.R.",
"Vinyl Vanna",
"Vegas 2.0",
"Using 4Chan for parenting advice",
"User Error",
"Undercover NBC DateLine Reporter",
"UDP Handshake",
"Two Girls One Cup",
"Truffle Shuffle",
"Trigger word",
"Tractor Beam",
"Toxic BBQ",
"I'm a text",
"Tongue punch that fart box, boy",
"TL;DR",
"Threat modeling",
"Throat Punching",
"There's talks at DEF CON?",
"The Spanish Inquisition",
"The smell of glitter and lost dreams",
"The plan was to crowd source a plan",
"The fractured elements of her psyche reassembled themselves into an exact likeness of a snarling ferret and she self-destructed",
"The asshole sitting to my right.",
"The asshole sitting to my left",
"That's What ~ She",
"That's Racist!",
"That place where I put that thing that time.",
"That just happened and we let that happen.",
"Tentacle Porn",
"TARDIS",
"Sweat, anger and shame",
"Stolen laptops",
"Sticky keyboard",
"Steve Wozniak",
"Steampunk",
"SRDF (Self Righteous Dick Face)",
"Squirrel",
"Spyware",
"Spotting a FED",
"SPAM with Bacon",
"Something something danger zone. I know. I'm not even trying anymore.",
"Spacedicks",
"Slow Clap",
"Six gummy bears and some scotch",
"Situational awareness",
"Shut up and take my money",
"Schr&ouml;dinger's cat",
"Shenanigans",
"Security theater",
"Security Evangelist",
"Security by obscurity",
"Script kiddies",
"Said no one ever!",
"Sabu",
"Running backwards through a corn field",
"Rule 34",
"Ruby on Rails",
"Rolling Natural 20's",
"ROFLCOPTER",
"Riding a horse",
"Ridiculously Photogenic Guy",
"Ribbed for their pleasure",
"Restore from backups",
"Redbull without a cause",
"Red Shirts",
"ReCaptcha",
"Real men of Genius",
"Rainbow tables",
"Rageface",
"Rage quit",
"Put Kevin back",
"Put a bird on it",
"Purchasing challenge coins on eBay",
"Prism",
"Priest in a thong doing the Gangnam Style",
"Pressing the red button",
"Prenda Law",
"Prairie dogging during an interview",
"Practicing Gringo Warrior at home with baby oil. Naked.",
"P0rn",
"PORK CHOP SANDWICHES!",
"Pop, Pop, Ret",
"Pool2Girl",
"Please do the needful",
"Pirate Party",
"Pepper spray",
"PedoBear",
"Patrick Star",
"Pastebin password files",
"Passwords emailed in plain text",
"Password: Guest",
"0wning You",
"Online backups",
"One Salty Hash",
"OMGBTFBBQ",
"Obvious",
"NSA",
"Now I'm into something... Darker",
"Not a single fuck was given",
"North Korea's Twitter Account",
"No Starch Press",
"No Reason",
"Nmap",
"Ninjas, Pirates, Robots, and Zombies!",
"Ninja badge",
"Nigerian scammers",
"Neck beard",
"NAMBLA",
"Na-ah-ah You didn't say the magic word!",
"My sex robot Fisto Roboto",
"My massive SSD",
"My little Bronies",
"My first Prostate Exam",
"Mouth Hugs",
"Mega",
"Mega Upload",
"Math is hard. Lets go shopping!",
"Masturbating in a hot tub for a Ninja Badge",
"Mansplaining",
"Maniacally laughing while wearing a monocle",
"Making a sandwich",
"Maintaining the Ballmer Peak",
"Lock picks",
"Level 8 Portal",
"Lemon Party",
"Learning something at Con",
"Lady boner",
"L0pht",
"Keyloggers",
"Kevin Mitnick",
"Kegels",
"Just the Tip",
"Just a sniff",
"Julian Assange",
"John McAfee",
"It's just a bunch of ones and zeros",
"It blended!",
"Ingress",
"Infected email attachments",
"In the cloud",
"Implied Situational Consent",
"Ill-tempered sea bass",
"If you know what I mean",
"Identity theft",
"ICANN",
"I should buy a boat",
"Humperdink award",
"HuBot (Chatroom bot)",
"Hookers & Blow",
"Hashtag",
"Handcuffs",
"Grumpy Cat",
"Gray beard, gray balls",
"Grammar Nazi",
"Got it done!",
"Good Guy Greg",
"Golf cart",
"Glasshole",
"Getting thrown the the pool by the Goons with all your tech",
"Getting hammered in the ass so much you die of getting hammered in the ass",
"Getting F'd in the A with a D",
"Getting a sympathy boner",
"Fyodor",
"FX",
"Forking someone's repo",
"Forever Alone",
"FOIA Request",
"Floppy Disk",
"Flipping a table",
"Flesh light",
"Flame wars",
"Fist full of assholes",
"Fish fingers and custard",
"First World Problems",
"Finished it last week!",
"FemiNazi's",
"Fear Uncertainty Doubt (FUD)",
"Fapping while wearing a horse head mask",
"Fapping on the family computer",
"Fapped",
"Facepalm",
"EXIF data stalking",
"End User License Agreement",
"Electronic Frontier Foundation",
"Edward Snowden",
"Drunken Muppet",
"Drones",
"Double ROT13",
"Double Facepalm",
"Don't Blink",
"Dr. Who",
"Dongs",
"Doing the '(you are) NOT the father' dance",
"Digital Millennium Copyright Act (DMCA)",
"Die in a fire",
"Dick and/or Balls",
"derp.rar (yo.zip)",
"Def Con Wireless",
"Do not connect to this!",
"Deep C Phishing",
"Dark Tangent",
"Dan Kaminsky Password Generator",
"Dan Kaminsky",
"Daaaaaanger Zone!",
"Cyber war",
"Cyber-douchery",
"Cyber Punk",
"Crying over spilt milk",
"Crash Override",
"Copyright trolls",
"Coding while listening to whale songs",
"Clicking shit",
"Chuck Norris",
"China",
"Check a look at you later",
"Cat memes",
"Caressing a man's hairy chest",
"Captain Crunch (John Draper)",
"Butthurt",
"Butt chugging mom's boxed wine",
"But then I'd have to kill you",
"Big Dongles",
"Big Data",
"Being the big spoon",
"Being the little spoon",
"Being sexually aroused by the sight of TSA's gloves",
"Bath salts",
"Bacon",
"Babe caught me slippin'",
"Awkward mouth hugs",
"Awkward hugs",
"Asymmetric encryption",
"Arbitrary code execution",
"APT1",
"Anonymous",
"And then it died",
"And boom goes the dynamite",
"An arrow to the knee",
"Altair 8800",
"All the Things!",
"Alexis Park",
"Ain't nobody got time for dat!",
"Ada Initiative approved flesh-light with anti-rape condom included!",
"ACTII pr0n",
"A van down by the river",
"A town with no ducks",
"A series of explicit Post-It notes",
"A series of tubes",
"A Raspberry Pi",
"A Payphone",
"A Ninja-tel Phone",
"A Hak5 Pineapple",
"A Googly eyed blow job",
"A giant cup of STFU",
"A fake ID made from Kinko's",
"A baby's arm holding an apple",
"A 'Pair of Docs'",
"64 Bit Keys",
"503 Card Unavailable",
"501 Card Error",
"500 internal card error",
"406 Not Allowed",
"404 Not Found",
"403 Forbidden",
"401 Unauthorized",
"3D printed P0rn",
"302 Card Redirect",
"10,000 Canadian Pennies",
"1.21 Jigawatts",
"(wub) (wub) (wub)",
"'I Survived Ada Camp' Challenge Coin",
"1337 Sp3ak",
"Making 77 cents on the dollar (unless you're Latina).",
"Inspirational Dove chocolate wrappers.",
"Masturbating to Ty Pennington.",
"Pretending you'll wear that bridesmaid dress again.",
"Mansplaining.",
"Beyonce thinkpieces.",
"Gabby Giffords' physical therapy.",
"Female genital mutilation.",
"When the tampon's too low and you feel it with every step.",
"A joke too funny for women to understand.",
"Meryl Streep selfies.",
"Hillary bitch-slapping Bill with a frozen tuna.",
"The Bechdel Test.",
"Staph infections from dirty nail salons.",
"Stalking wedding photos on Facebook, weeping softly.",
"Emma Goldman burning the whole motherfucker down.",
"Douches that smell like rain.",
"Rosa Parks' back seat.",
"Engagement photos on train tracks.",
"Choking on the ashes of Gloria Steinem's bras.",
"The cold, hard truth that no lesbian has ever scissored.",
"Doing your kegels at work.",
"Misandry.",
"Abortion Barbie.",
"Telling a street harasser \"You know what? I <i>will</i> blow you.\"",
"Peggy Olson's cutthroat ambitions.",
"A quickie with Rachel Maddow in the green room.",
"Force-feeding Sheryl Sandberg the pages of Lean In, one by one.",
"Emma Watson, Emma Stone, EMMA THOMPSON BITCHES.",
"Dumpsters overflowing with whimisical save-the-date magnets.",
"The torture chamber where Kathryn Bigelow keeps James Cameron.",
"A detailed vajazzling of Van Goh's Starry Night.",
"STOP MAKING ME PRETEND TO CARE ABOUT YOUR WEDDING PINTEREST DARLA.",
"The Chub Rub.",
"Chin hairs you pretend you don't have.",
"A strongly worded letter to Netflix demanding the addition of \"The Good Wife\".",
"Doubling up on sports bras.",
"When a dog smells your crotch and you know exactly why.",
"Malala's gunshot wounds.",
"Lactating when a stranger's baby cries on the train.",
"A new cookbook by Sylvia Plath.",
"Crying in the fitting room during bikini season.",
"Eating the entire bag.",
"Scalding hot wax right there on your labia.",
"The G-Spot, the Y-spot, the other spot you made up to confuse your partner.",
"The Golden Girls' never-ending supply of frozen cheesecake.",
"Underboob swet like rancid milk.",
"Wondering whether your girl crush on Hermione constitutes pedophilia.",
"Taking a giant dump on the 18th green at the Augusta National Golf Club.",
"A brown smudge equally likely to be period blood or chocolate.",
"A hand-crocheted Diva Cup case from Etsy.",
"Your gigantic crush on Jenna Lyons.",
"A one-way ticket to Steubenville.",
"A bodice-ripping 4-way with Alexander Skarsgard, Ian Somerhalder, and David Boreanaz.",
"Finger banging Michelle Rodriguez.",
"Princess Aurora maniacally devouring the still-beating heart of Maleficent.",
"A tear stained copy of Reviving Ophelia.",
"A misogynist dystopia set in a not-too-distant WAIT A MINUTE.",
"Dying your hair red like Angela Chase.",
"Daenerys Targaryen's fire-breathing vajayjay.",
"Resentfully clicking like on your boss's vacation photos.",
"Calmly informing your date that you understand the infield fly rule better than he does.",
"Tina Fey and Amy Poehler making out on a pile of Bitch magazines.",
"Only shaving up to the knee.",
"Meredith Grey's slut phase.",
"Shameful childhood memories of envying the wheelchair girl who got all the attention.",
"Sort of wishing the baby on the plane would die.",
"Tenderly dominating Uncle Jesse from behind.",
"Stumbling on David Wright performing as Judy Garland in the East Village.",
"Urinating on yourself to prevent an assault.",
"When a FOX News anchor causally references 'ebonics'.",
"Getting DPed by the Property Brothers on a custom granite countertop.",
"Being compared to a Cathy Cartoon on Metafilter.",
"Kim Kardashian's placenta banh mi.",
"Asking Gilbert Gottfried to do the Iago voice during sex.",
"Watching Bethenny Frankel struggle for life in a churning sea of pre-mixed SkinnyGirl cocktails.",
"An alternate version of the Washington Monument that looks kind of like a vagina.",
"Telling Pacey your innermost secrets in a canoe beneath the Capeside stars.",
"The blue liquid from tampon commercials.",
"Patti Stanger's line of jewelry.",
"#solidarityisforwhitewomen.",
"A candlelight vigil for Nicole Brown Smith.",
"Sexual fantasies involving Mindy Lahiri and a sumptuous coffeecake.",
"Tweeting Cory Booker about that guy walking behind you.",
"A gender-neutral, owl-themed baby announcement.",
"Being the only woman at the office-mandated sexual harassment training.",
"Asking Larry Summers increasingly difficult mathematical questions until Bar and Mat Mitzvahs are considered equally important.",
"Cramming Vladimir Putin full of Activia until he poops out Russia's homophobia."
]
}
